name: flutter_getx
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^0.1.3

  #GetX
  get: ^3.13.2

  #UTILS
  ns_utils:
    git: https://github.com/ajaynonstopio/ns_utils.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true